# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ImportRecipesJob`.
# Please instead update this file by running `bin/tapioca dsl ImportRecipesJob`.


class ImportRecipesJob
  class << self
    sig do
      params(
        source_url: T.untyped,
        file_path: T.untyped,
        block: T.nilable(T.proc.params(job: ImportRecipesJob).void)
      ).returns(T.any(ImportRecipesJob, FalseClass))
    end
    def perform_later(source_url: T.unsafe(nil), file_path: T.unsafe(nil), &block); end

    sig { params(source_url: T.untyped, file_path: T.untyped).returns(T.untyped) }
    def perform_now(source_url: T.unsafe(nil), file_path: T.unsafe(nil)); end
  end
end
